apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: worker-service
  name: worker-service
spec:
  replicas: {{ .Values.services.apps.replicaCount }}

  selector:
    matchLabels:
      io.kompose.service: worker-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: worker-service
    spec:
      containers:
      - env:
        - name: CLUSTER_PORT
          value: {{ .Values.services.worker.port | quote }}
        - name: COUCH_DB_PASSWORD
          value: {{ .Values.services.couchdb.password | quote }}
        - name: COUCH_DB_URL
          value: {{ .Values.services.couchdb.host | quote }}
        - name: COUCH_DB_USERNAME
          value: {{ .Values.services.couchdb.username | quote }}
        - name: INTERNAL_API_KEY
          value: {{ .Values.globals.internalApiKey | quote }}
        - name: JWT_SECRET
          value: {{ .Values.globals.jwtSecret | quote }}
        - name: MINIO_ACCESS_KEY
          value: {{ .Values.services.object_store.accessKey }}
        - name: MINIO_SECRET_KEY
          value: {{ .Values.services.object_store.secretKey }}
        - name: MINIO_URL
          value: {{ .Values.services.object_store.url }}
        - name: PORT
          value: {{ .Values.services.worker.port | quote }}
        - name: REDIS_PASSWORD
          value: {{ .Values.services.redis.password | quote }}
        - name: REDIS_URL
          value: "{{ .Values.services.redis.host }}:{{ .Values.services.redis.port }}"
        - name: SELF_HOSTED
          value: {{ .Values.globals.selfHosted | quote }}
        image: budibase/worker
        imagePullPolicy: ""
        name: bbworker
        ports:
        - containerPort: {{ .Values.services.worker.port }}
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status: {}
