apiVersion: v1
kind: Secret
metadata:
  name: {{ template "posthog.fullname" . }}
  labels:
    app: {{ template "posthog.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.posthogSecret }}
  posthog-secret: {{ .Values.posthogSecret | b64enc | quote }}
  {{ else }}
  posthog-secret: {{ randAlphaNum 40 | b64enc | quote }}
  {{ end }}
  {{ if or (not .Values.postgresql.enabled) (.Values.postgresql.password) }}
  postgresql-password: {{ .Values.postgresql.postgresqlPassword | default "" | b64enc | quote }}
  {{ end }}
  {{ if and (not .Values.redis.enabled) (.Values.redis.password) }}
  redis-password: {{ .Values.redis.password | default "" | b64enc | quote }}
  {{ end }}
  {{- if not .Values.email.existingSecret }}
  smtp-password: {{ default "" .Values.email.password | b64enc | quote }}
  {{ end }}
